name: AWS-EC2 Instance CD
on:
  workflow_run:
    workflows: ["Node.js CI"]
    types: [completed]

    jobs:
      on-success:
        runs-on: ubuntu-latest
        if: github.event.workflow_run.conclusion == 'success'
        steps:
          - name: AWS SSM send command
            uses: peterkimzz/aws-ssm-send-command@v1.1.1
            with:
              #AWS access key id
                aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              #AWS secret access key
                aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                #AWS region
                aws-region: ${{ secrets.AWS_REGION }}
                #AWS EC2 instance id
                instance-id: ${{ secrets.INSTANCE_ID }}
                #Command execution location
                working-directory: /home/ubuntu
                #Command to execute
                command: |
                  sudo docker-compose stop
                  sudo docker-compose pull
                  sudo docker-compose up -d
                  sudo docker-compose rm -f
                  sudo docker image prune -af
                #Comment for Send-Command
                comment: docker-compose.yml file re-pulls newer versions of allergen-app images and runs on the EC2 instance





