name: AWS-EC2 Instance CD

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types: [completed]

jobs:
  on-success:
    
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: AWS SSM send command
        uses: peterkimzz/aws-ssm-send-command@v1.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          instance-id: ${{ secrets.INSTANCE_ID }}
          working-directory: /home/ubuntu
          command: |
            sudo docker-compose stop
            sudo docker-compose pull
            sudo docker-compose up -d
            sudo docker-compose rm -f
            sudo docker image prune -af
          comment: |
            Docker Compose file re-pulls newer versions of all allergen-app images and runs on the EC2 instance
