name: Java CI with Gradle

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_TWO }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push BE
        uses: docker/build-push-action@v2
        with:
          context: ./allergen-web-app-back-end
          file: ./allergen-web-app-back-end/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/allergen-web-app-allergen-be:latest
